export const CHANGELOG = [
  {
    version: 'v2.54',
    date: '2026-10-08',
    title: 'Vimsottari Utpanna / Kshema / Adhana',
    changes: [
      'New daśā system, Vimsottari Utpanna / Kshema / Adhana, in TIMING and everywhere the daśā systems are listed (Systems, Slider, Yearly, Event List, Summary, the date finder and the timeline). It starts the Vimsottari from the lord of the 5th (Utpanna), 4th (Kshema) or 8th (Adhana) nakshatra counted from the Moon’s, with the balance taken from the Moon’s own longitude.',
      'The system picks the start from the Moon: the one of the three whose sign has the most grahas in the angles is the strongest; ties go to the one the lord of its nakshatra, Jupiter or Mercury joins or aspects, then to Utpanna, Kshema, Adhana in that order. The card shows the three candidates with their nakshatra, lord and strength, and marks the one in use.',
      'Settings → dasha methods has a start from choice: the strongest (auto), or Utpanna, Kshema or Adhana fixed.',
      'The daśā lords on the charts (ᴹ ᴬ marks and the dasha houses) can come from the new system too. The ··· menu of the chart now has a dasha lords from choice, and hovering a lord’s house names the system the lords come from.',
      'Updated the application version to v2.54.',
    ],
  },
  {
    version: 'v2.53',
    date: '2026-10-08',
    title: 'Upagrahas, Karakamsa and the pada table',
    changes: [
      'Special Sphutas in ANALYSIS now also lists the upagrahas: Gulika and Maandi (the Lagna rising in Saturn’s part of the day or night) and the Sun-based Dhuma, Vyatipata, Parivesha, Indrachapa and Upaketu, each with its sign, longitude, house, nakshatra and pada.',
      'Traditions take the Lagna at different moments of Saturn’s part, so Gulika and Maandi each have a choice of the beginning, the middle or the end of the part (Gulika starts at the beginning and Maandi at the middle).',
      'New Jaimini points: Karakamsa (the sign of the Atmakaraka in the Navamsa, read from the Lagna) and Svamsa (the same sign read in the Navamsa chart), following the chosen karaka scheme, and a table of the Arudha padas AL … AL12 (AL12 marked UL) with their sign, degree and the house they fall in.',
      'Updated the application version to v2.53.',
    ],
  },
  {
    version: 'v2.52',
    date: '2026-10-08',
    title: 'Dasha houses on the charts',
    changes: [
      'The houses of the running mahadasha and antardasha lords get a coloured border on the North and South charts: cyan for the mahadasha lord’s house and pink for the antardasha lord’s house (hover for the lord). Before, only the small ᴹ and ᴬ marks on the planets showed them.',
      'The borders are a layer of their own, dasha houses, switched on and off in the ··· menu of the chart or in Settings, separately from the dasha lords marks. The Vargas grid and the pinned chart follow the same switches.',
      'Updated the application version to v2.52.',
    ],
  },
  {
    version: 'v2.51',
    date: '2026-10-08',
    title: '7 or 8 chara karakas',
    changes: [
      'Settings has a new chara karaka scheme choice: eight karakas (Rahu included, with the Pitrikaraka) or seven (without Rahu and the Pitrikaraka). Either scheme can be ranked by degrees or by minutes, with the ranking choice that was already there.',
      'The charts, the grahas table and the report follow the choice, and the Chara dasha that starts from the Atmakaraka finds it the same way.',
      'Updated the application version to v2.51.',
    ],
  },
  {
    version: 'v2.50',
    date: '2026-10-08',
    title: 'All Arudha padas at once',
    changes: [
      'The arudha padas section of the ··· menu has an all button beside none, which marks AL and AL2 … AL12 on the charts in one go.',
      'Updated the application version to v2.50.',
    ],
  },
  {
    version: 'v2.49',
    date: '2026-10-08',
    title: 'Arudha padas on the charts',
    changes: [
      'The Āruḍha padas can be marked on the charts: AL (the pada of the 1st house) and AL2 … AL12 (the padas of the other houses; AL12 is the Upapada). Choose them in the ··· menu of the chart, under arudha padas; the chips switch each pada on and off, and none clears them.',
      'The padas are worked out in each chart: the divisional charts (D9, D10 …), the Vargas grid and the pinned chart mark them in their own division. The choice is remembered and shared by all the charts.',
      'Each pada stands as far from the house lord as the lord stands from the house, with the lord’s degree; a pada that falls in the house itself or its 7th gives way to the 10th from it.',
      'Updated the application version to v2.49.',
    ],
  },
  {
    version: 'v2.48',
    date: '2026-10-08',
    title: 'Special Sphutas',
    changes: [
      'New Special Sphutas view in ANALYSIS: Bhava, Hora, Ghati and Pranapada Lagna, Sree Lagna, Bhrigu Bindu, Arudha Lagna, the 22nd Drekkana, the 64th Navamsa, Indu Lagna, Varnada Lagna and Vighati Lagna, each with its sign, longitude (to hundredths of a second), nakshatra and pada.',
      'The special lagnas on the charts (HL, BL, GL, SL, PP, ViL) are now worked out properly. Before, the time-based ones ran on the clock time of the day and Sree Lagna was the midpoint of the Lagna and the Moon. Now Bhava, Hora, Ghati, Vighati and Prana run on the time since sunrise from the Sun at birth (6, 12, 30 and 1800° and 4° per ghati), and Sree Lagna turns the Lagna by the fraction of its nakshatra the Moon has passed.',
      'Settings: the sunrise for the special lagnas, mean-time (the true sunrise plus the equation of time, the default) or the true sunrise. The Special Sphutas view also has a field for typing in another sunrise, for example the one another program shows.',
      'Updated the application version to v2.48.',
    ],
  },
  {
    version: 'v2.47',
    date: '2026-10-08',
    title: 'Rao Sir System of Nadi',
    changes: [
      'The Nadi system is now named the Rao Sir System of Nadi (RSN) instead of BNN: the chart labels (RSN Maj, RSN Min), the layer names (RSN major, RSN minor) and the texts. Settings → chart layers explains the abbreviation. The calculations are unchanged.',
      'Updated the application version to v2.47.',
    ],
  },
  {
    version: 'v2.46',
    date: '2026-10-08',
    title: 'Daśā columns and notes, Slider, Yearly, event transits, graha names',
    changes: [
      'Systems: the daśā systems can stand side by side, 1 to 4 columns (columns buttons, from a tablet up). The ⤢ wide button above the timing tabs gives the timing panel the whole width of a wide screen and hides the chart. A system whose mahādaśā ends within a year shows a flag “MD changes 03.2027” in its header.',
      'Every daśā system has a note field at the top of its open card, kept in the browser with the chart. A ✎ in the header shows that a note exists. (The events already had their own notes.)',
      'New Slider view: drag through time, from birth to 100 years on, and read the running MD – AD – PD of every system. New Yearly view: a table with a row for each year (21 at a time) and a column for each system; a new MD (amber) or AD (blue) is marked.',
      'Events: the Transits on the charts button, or resting the pointer on an event, shows the transits of the event’s day (noon, natal time zone) on the natal charts in the chosen divisional charts (D1, D9, D10 …).',
      'The tab transit.hits is now called Transit Hits.',
      'Graha names are in English: the graha table (ANALYSIS → Grahas) and the Finnish interface no longer show Sūrya, Chandra, Kuu, Saturnus and so on. Settings → graha names switches to the Sanskrit names (Sūrya, Candra, Maṅgala, Budha, Guru, Śukra, Śani, Rāhu, Ketu) and their short codes (Su Ch Ma Bu Gu Sk Sa Ra Ke) on the charts, the graha table, the daśā periods and the new views.',
      'Updated the application version to v2.46.',
    ],
  },
  {
    version: 'v2.45',
    date: '2026-10-08',
    title: 'Paraya speed options',
    changes: [
      'Settings has two new choices for the Paraya: Saturn either 3 / 2 years alternating (as before) or 2.5 years in every sign, and Rahu / Ketu either 2 / 1 years alternating (as before) or 1.5 years in every sign. A round still takes 30 years for Saturn and 18 for Rahu.',
      'The choices apply to the Paraya houses on the chart and to the Paraya hits.',
      'Updated the application version to v2.45.',
    ],
  },
  {
    version: 'v2.44',
    date: '2026-10-08',
    title: 'No 1 / 5 / 9 buttons',
    changes: [
      'Removed the 1, 5 and 9 buttons from transit.hits. The transit hits are the point itself, as before v2.42; the Paraya hits always include the 1st, 5th and 9th.',
      'Updated the application version to v2.44.',
    ],
  },
  {
    version: 'v2.43',
    date: '2026-10-08',
    title: 'Paraya hits',
    changes: [
      'transit.hits has a new Paraya hits section: when the Paraya Jupiter, Saturn, Rahu and Ketu (moved by age) reach each natal graha or the ascendant, and the same degree in its 5th and 9th sign. Each row has the date, the age and a “set target” button. The buttons 1, 5 and 9 choose the houses, and 1, 3 or 10 years the period from the target date.',
      'The 5th and 9th buttons added to the real transit hits in v2.42 stay, but are off to start with, so that list is as it was; the Summary lists only the point itself again.',
      'Updated the application version to v2.43.',
    ],
  },
  {
    version: 'v2.42',
    date: '2026-10-08',
    title: 'Transit hits to the 5th and 9th',
    changes: [
      'Transit hits now also lists when Jupiter, Saturn, Rahu and Ketu reach the same degree in the 5th and the 9th sign from each natal graha and the ascendant, not only the point itself. The buttons 1, 5 and 9 above the list choose which houses count; all three are on to start with.',
      'The Summary view lists the same hits.',
      'Updated the application version to v2.42.',
    ],
  },
  {
    version: 'v2.41',
    date: '2026-10-08',
    title: 'Nava-Tara chakra and the direction chart',
    changes: [
      'New Nava-Tara view in ANALYSIS: the 27 nakshatras in nine Taras (Janma, Sampat, Vipat, Kshema, Pratyari, Sadhaka, Vadha, Mitra, Ati-Mitra), counted from the Moon’s nakshatra or from the ascendant’s, with the natal grahas standing in them. The Transit button adds the transiting grahas.',
      'New Directions view in ANALYSIS: a large cross with the north, east, south and west, and the grahas standing in each, by sign (fire east, earth south, air west, water north) or by house from the ascendant (1st east, 4th north, 7th west, 10th south). A star marks a graha in the direction where it has Dig Bala. The Transit button adds the transits.',
      'Updated the application version to v2.41.',
    ],
  },
  {
    version: 'v2.40',
    date: '2026-10-08',
    title: 'Timing summary',
    changes: [
      'New Summary view in TIMING: for the target day, the running daśā periods of every enabled system, the next sign changes, stations and combustions, and the next transit hits, all on one page.',
      'The Print / PDF button prints only the summary, so the browser can save it as a PDF.',
      'Updated the application version to v2.40.',
    ],
  },
  {
    version: 'v2.39',
    date: '2026-10-08',
    title: 'Pinned chart on the phone',
    changes: [
      'On a phone, TIMING keeps the chart at the top of the screen while the daśās scroll underneath. It shows the same D1 / D9 / D10 (or other divisional) charts as the main chart, can be changed with the same buttons, and folds away with the ▲ button.',
      'Updated the application version to v2.39.',
    ],
  },
  {
    version: 'v2.38',
    date: '2026-10-08',
    title: 'Divisional charts next to the daśās',
    changes: [
      'The chart has a D1 / D9 / D10 selector, and a “+ more” list for the other divisions. Choose one or several: several are drawn side by side, so on a wide screen they stay on the left while TIMING, with the daśās, is open on the right.',
      'One chart alone is drawn full size (D1 with all its layers). Tap a chart’s title to show that chart alone. Tap a planet to follow it through every chart. The choice is remembered.',
      'Updated the application version to v2.38.',
    ],
  },
  {
    version: 'v2.37',
    date: '2026-10-08',
    title: 'Running periods, stations, touch targets',
    changes: [
      'Each daśā system in TIMING → Dasha → Systems shows its running periods in the closed header, for example “Rahu – Rahu – Moon · MD → 05.2042”, for the target date.',
      'Sign changes also lists stations (when Mars, Mercury, Venus, Jupiter and Saturn turn retrograde or direct) and when Mercury and Venus enter or leave combustion. The “stations & combustion” button switches them off.',
      'Phone: the on/off switches in the ··· menu, the graha and period buttons and “set transit” are larger to tap, and a sign and its house no longer split across two lines.',
      'Updated the application version to v2.37.',
    ],
  },
  {
    version: 'v2.36',
    date: '2026-10-08',
    title: 'Daśā systems start closed',
    changes: [
      'In TIMING → Dasha → Systems every daśā system now starts closed, listed by name. Open the one you want; the others are not drawn until opened.',
      'Updated the application version to v2.36.',
    ],
  },
  {
    version: 'v2.35',
    date: '2026-10-08',
    title: 'Sign changes of the grahas',
    changes: [
      'New Sign changes view in TIMING: when each graha moves into the next sign, from the target date, to the minute. Each row shows the new sign and its house from the natal ascendant; ℞ marks a move backwards.',
      'Choose the grahas (the Moon is off by default, since it changes sign every two to three days) and the period: 1, 3 or 12 months. “set transit” moves the transit chart to that moment.',
      'Updated the application version to v2.35.',
    ],
  },
  {
    version: 'v2.34',
    date: '2026-10-07',
    title: 'A cleaner chart',
    changes: [
      'Removed the legend under the chart (BCP, BNN, Paraya, daśā lords, Transit); the layers are switched in the ··· menu.',
      'Removed the ayanamsa, node and time zone line under the chart. The footer shows only the version.',
      'The BNN minor house outline is now a solid line instead of dashed.',
      'Updated the application version to v2.34.',
    ],
  },
  {
    version: 'v2.33',
    date: '2026-10-07',
    title: 'Chart layers behind the ··· menu',
    changes: [
      'The chart layer switches are now ON/OFF buttons at the top of the ··· menu next to the chart: Transit, BCP year/month, BNN major, BNN minor, Paraya and the daśā lords. The separate Transit button is gone.',
      'Added tools/llm_router, a LiteLLM based router that picks DeepSeek or OpenAI by task type.',
      'Updated the application version to v2.33.',
    ],
  },
  {
    version: 'v2.32',
    date: '2026-10-06',
    title: 'One target moment, transits included',
    changes: [
      'The target is now a moment, a date and a time, and the transits follow it too. Step it by an hour, day, month or year, type a date and time, or press “now”. The separate transit date field below the chart is gone.',
      'BCP, BNN, Paraya and the daśā lords read the target date; the transits are calculated for the exact date and time. While they recalculate, the bar shows “transits…”.',
      '“Set as target” in the Dasha event list, and “set transit” in the transit hits, move the whole target moment. Saved charts remember the target time.',
      'Layers that are switched off no longer appear in the chart legend; switch them back on under Settings → chart layers.',
      'Updated the application version to v2.32.',
    ],
  },
  {
    version: 'v2.31',
    date: '2026-10-06',
    title: 'Target date controls, transit hits, Finnish',
    changes: [
      'The target date now has its own controls above the chart: step back or forward a day, month or year, pick a date, or return to today. BCP, BNN, Paraya, the daśā lords and the annual charts all follow it at once, without recalculating the chart.',
      'Transit hits lists the twelve months after the target date: when Jupiter, Saturn, Rahu and Ketu cross a natal graha or the ascendant, to the day, retrograde passes marked ℞. “Set transit” moves the transit chart to that day.',
      '“Open in chart” in the Dasha event list sets the target date and the transits to the event’s day and shows the chart.',
      'The daśā lord marks can follow Vimśottarī, Vimśottarī Original, Yoginī or Aṣṭottarī (Settings → chart layers). The legend names the system.',
      'Planets in the Varga charts are coloured by dignity: exalted green, own sign blue, debilitated red.',
      'The interface can be switched to Finnish (Settings → display → language). Navigation, birth data, settings, chart views and legends are translated; the detailed analysis tables are still in English.',
      'Updated the application version to v2.31.',
    ],
  },
  {
    version: 'v2.30',
    date: '2026-10-06',
    title: 'Daśā lords on the chart, BCP back as a layer, chart export',
    changes: [
      'The running Vimśottarī lords at the target date are marked on the natal planets: ᴹ for the mahādaśā lord, ᴬ for the antardaśā lord, in the chart and in every Varga chart. The legend names them and switches the marks off and on.',
      'The BCP running year and month houses can be shown again, as a chart layer that is off by default (v1.80 took them off the chart). Turn it on under Settings → chart layers or from the legend.',
      'Following a planet in the Varga view now lists its sign in every chart shown, with exaltation ↑, own sign ◆ and debilitation ↓ coloured, and the signs that repeat its D1 sign underlined.',
      'The chart and a full-size Varga chart can be downloaded as PNG or SVG.',
      'Settings → display now opens on the calculation settings only; chart style, overlays, layers and daśā systems are collapsed until opened.',
      'Added a browser test that calculates a chart and opens every main view on a phone and a desktop screen; it runs on every pull request.',
      'Split the main page: settings storage and the values worked out from the chart now live in their own hooks, and the header, date helpers and daśā-settings migration in their own files. Nothing changes in use.',
      'Updated the application version to v2.30.',
    ],
  },
  {
    version: 'v2.29',
    date: '2026-10-06',
    title: 'BCP manual mode removed',
    changes: [
      'Removed the manual BCP age and month entry. It had no controls left in the app, so BCP always followed the target date anyway; the unused code is now gone.',
      'Updated the application version to v2.29.',
    ],
  },
  {
    version: 'v2.28',
    date: '2026-10-06',
    title: 'Workspace removed, Varga fixes',
    changes: [
      'Removed the workspace (the WS tab and the “workspace mode” setting). The Varga view with full screen now covers the side-by-side use. Saved workspace layouts are cleared and are no longer part of backups.',
      '“Open Varga Matrix” in the Dasha event list now opens Matrix & Bala; it used to open the charts.',
      'Small South Indian charts in the Varga view use one column on a phone, so their cells are large enough to read. Wider screens still show several per row.',
      'Updated the application version to v2.28.',
    ],
  },
  {
    version: 'v2.27',
    date: '2026-10-06',
    title: 'One Varga view',
    changes: [
      'Merged Varga and Vargas into one Varga view. It opens on the divisional charts side by side; Matrix & Bala is beside it as before.',
      'A chart’s title opens it full size with everything the old single-chart view had: special lagnas, karakas, degrees, nakṣatras in D1, the divisional lagna and what the chart is read for.',
      'Updated the application version to v2.27.',
    ],
  },
  {
    version: 'v2.26',
    date: '2026-10-06',
    title: 'Full screen, sixteen vargas',
    changes: [
      'The chart views (Chart, Varga, Vargas, Nāḍī and the rest) can be opened full screen with the “full” button beside their tabs. Charts grow to fill the screen. Close with the button or Esc; on a computer the browser’s own full screen is used too.',
      'Vargas now shows up to sixteen charts at once. Added the Daśavarga (ten charts) and Ṣoḍaśavarga (all sixteen) groups, and a custom selection can hold four to sixteen. Wide screens show five or six charts per row.',
      'Updated the application version to v2.26.',
    ],
  },
  {
    version: 'v2.25',
    date: '2026-10-06',
    title: 'One mode',
    changes: [
      'Removed the simple / research / debug switcher from the header. The app now always works as simple mode did.',
      'The calculation details (Julian day, ayanamsa, ascendant degree, coordinates) are still there: the collapsed “calculation details” line under the graha table opens them.',
      'Updated the application version to v2.25.',
    ],
  },
  {
    version: 'v2.24',
    date: '2026-10-06',
    title: 'Vargas: divisional charts side by side',
    changes: [
      'Added a Vargas view next to Varga that shows several divisional charts side by side: two columns on a phone, three or four on wider screens.',
      'Choose Ṣaḍvarga (D1 D2 D3 D9 D12 D30, the default), Saptavarga (adds D7), or any four to eight charts of your own. The choice is remembered.',
      'Tap a planet, in a chart or in the row of planet buttons, to follow it through every chart. Tap a chart’s title to see it full size with the usual degree and karaka settings.',
      'The small charts show planet codes only, in larger type, and work in both North and South Indian style.',
      'Updated the application version to v2.24.',
    ],
  },
  {
    version: 'v2.23',
    date: '2026-10-06',
    title: 'Crowded houses fit, legend switches',
    changes: [
      'Labels in a crowded house no longer run over its edges or get cut off. In the North Indian chart they flow into rows that follow the shape of the house, and the font shrinks only as far as that house needs. Short transit codes share a row (Mo Ma Ju). The South Indian chart fits each cell the same way, sized to the cell as drawn on screen.',
      'The Transit, BNN Major, BNN Minor and Paraya entries in the chart legend are now switches: click one to hide that layer, click again to bring it back. A hidden layer stays in the legend, dimmed and struck through.',
      'Removed display settings that nothing used: the four old BNN switches, Sanskrit names, and the old transit switch. They are dropped from saved settings when the app loads.',
      'BNN Major, BNN Minor and the Paraya points are now worked out in one place, so the chart and the workspace always agree, including with an age override.',
      'Added tests for the label layout, the North and South Indian charts (ascendant degree, legend switches, hidden layers), the saved-settings migration, the BNN houses, and a check that every display setting is actually used.',
      'Updated the application version to v2.23.',
    ],
  },
  {
    version: 'v2.22',
    date: '2026-10-06',
    title: 'Chart layer switches and ascendant degree',
    changes: [
      'Added a chart layers group under Settings → display with switches for the transit planets, the BNN Major and BNN Minor houses, and the Nāḍī Paraya points (Ju Sa Ke Ra). Each switch hides the layer and its legend entry in the North and South Indian charts and in the workspace charts.',
      'The ascendant degree is now shown in the 1st house of the natal chart, as “Asc 12°34′”. It follows the degree precision setting and shows degrees and minutes when that is off.',
      'Fixed: the old transit switch was not connected to anything, so transits always showed once calculated.',
      'Updated the application version to v2.22.',
    ],
  },
  {
    version: 'v2.21',
    date: '2026-10-04',
    title: 'Rāśi daśās checked against PyJHora and the book',
    changes: [
      'Nārāyaṇa, Lagna Kendrādi (Mūla) and Sthira Daśā now agree with PyJHora on every one of the fixture charts, and Nārāyaṇa reproduces both worked examples in P.V.R. Narasimha Rao’s book. Before this release one of the two book examples came out wrong.',
      'Fixed: Uranus, Neptune and Pluto were counted as occupants when deciding the stronger of lagna and 7th, which could pick the wrong starting sign for all three daśās.',
      'Fixed: Scorpio and Aquarius now use the stronger of their two lords (Mars or Ketu, Saturn or Rahu) for the period length, as the book requires. Scorpio and Aquarius periods could previously be several years off.',
      'The stronger-sign test now applies all six rules, adding Jupiter, Mercury and the lord joining or aspecting the sign, and the lord’s parity. Brahma for Sthira Daśā now follows PyJHora’s selection.',
      'Two of the earlier hand-derived regression charts disagreed with PyJHora and were replaced with PyJHora’s own output.',
      'Avasthā ghaṭīs now count from the ephemeris sunrise, like the Pañcāṅga.',
      'Updated the application version to v2.21.',
    ],
  },
  {
    version: 'v2.20',
    date: '2026-10-04',
    title: 'Varṣaphala, annual daśās, and Pañcāṅga from sunrise',
    changes: [
      'Added Tājika Varṣaphala as a new view: the chart for the Sun’s sidereal return, with day or night year, Muntha, the five office bearers and their Tājika aspects on the annual lagna, Pañcavargīya Bala, the lord of the year, and the Mudda (Varṣa Vimśottarī) daśā. Rules follow P.V.R. Narasimha Rao, chapters 28–30, and are tested against the book’s worked examples.',
      'Tithi Praveśa now shows its Tithi Aṣṭottarī daśā for the year (beta), and both annual charts can be cast for the place of residence that year instead of the birthplace.',
      'Tithi Praveśa is now checked against PyJHora: the same dates, within three minutes.',
      'Fixed the Pañcāṅga vāra and horā for births before sunrise, which belong to the previous weekday. Both are now counted from the ephemeris sunrise and sunset.',
      'The Pañcāṅga māsa is now the real amānta lunar month, with adhika months labelled, instead of an estimate from the Sun’s sign. Saham day and night births also use the ephemeris sunrise and sunset.',
      'Cleared all 64 lint warnings and made any new warning fail the check. Removed the unused transits endpoint, an empty script, and an unwired report-export handler.',
      'Updated the application version to v2.20.',
    ],
  },
  {
    version: 'v2.19',
    date: '2026-10-04',
    title: 'Tithi Praveśa annual chart',
    changes: [
      'Added Tithi Praveśa, the Vedic annual chart, as a new view beside Varga, Nāḍī, Aṣṭakavarga and Dṛṣṭi. It is cast for the moment the Moon returns to its natal distance from the Sun — the birth tithi to the arc-second — in the lunar month of birth.',
      'The lunar month is amānta and named by the Sun’s sidereal sign at the opening new moon. In an adhika year the nija month is taken, as tradition prescribes. A second method, the repetition nearest the solar return, is available as a toggle.',
      'Shows the start and end of the year with their own daylight-saving offsets, completed age, the natal tithi and māsa, the vāra counted from sunrise with its lord as lord of the year, and the running horā.',
      'The chart is drawn in the selected North or South Indian style with an optional natal overlay, plus a table giving each graha’s house in both the annual and the natal chart. Step through the years with the arrows, or return to the year in force at the target date.',
      'Added tests: the new moon finder against the 8 April 2024 eclipse, the elongation repeating across thirteen years, year lengths of twelve or thirteen lunations, the adhika Śrāvaṇa of 2023, New Year birthdays, and vāra and horā around sunrise.',
      'Updated the application version to v2.19.',
    ],
  },
  {
    version: 'v2.18',
    date: '2026-08-13',
    title: 'Boundary rounding fix, and tests for dṛṣṭi, VDS and panchāṅga',
    changes: [
      'Fixed a rounding fault that placed a body sitting exactly on a sign or nakṣatra boundary in the previous one. The same fault was corrected for the divisional charts in v2.14; it turned out to be present in fifteen further places, including the ephemeris itself, where it affected the sign of every planet.',
      'Affected: planet signs and houses, Panchāṅga nakṣatra and pada, Yoginī and Aṣṭottarī Daśā, Nāḍī aṁśa, sahams, and the nakṣatra labels on both chart styles. All longitude normalization now goes through one shared, tested helper.',
      'Added tests for Dṛṣṭi, which had none: the special graha aspects, and the mutual symmetry of Jaimini rāśi dṛṣṭi across all twelve signs.',
      'Added tests for Vimśottarī Original (VDS), covering both nakṣatra cycles, the pakṣa and horā selection rule, and the birth balance. Cross-checked against the standard Vimśottarī implementation.',
      'Added tests for Panchāṅga: tithi, nakṣatra and pada, yoga, karaṇa, vāra and horā.',
      'Removed the unused BNN module and the superseded Chara Daśā implementation with its two orphaned panels.',
      'Updated the application version to v2.18.',
    ],
  },
  {
    version: 'v2.17',
    date: '2026-08-13',
    title: 'Divisional charts, and tests for the core calculations',
    changes: [
      'Added divisional chart drawing: every varga from D1 to D60 can now be viewed as a North or South Indian chart, not just as a table. Houses are counted from the divisional ascendant and degrees show the position within the divisional sign.',
      'The Varga tab now has a Charts view alongside the existing Matrix & Bala table.',
      'Added tests for Vimśottarī, which had none: the nine lords summing to exactly 120 years, the 27 nakṣatra to lord mapping, birth balance and sub-period proportionality at every level.',
      'Added tests for the BCP progression, the application namesake, which also had none.',
      'Added coverage for D40, D45 and D60 across all twelve signs and every part; the varga fixtures previously stopped at D30 even though all three feed Viṁśopaka Bala.',
      'Added tests for the yoga engine, which had none across its 818 lines.',
      'Yoga strength is now classified per participating planet rather than on the raw sum, so the label no longer depends on how many planets a yoga happens to name. A three-planet yoga of ordinary planets previously read Weak while a two-planet yoga of the same quality read Moderate. The displayed number is unchanged.',
      'Cleared the remaining lint errors and made lint a blocking check, so new violations now fail the build.',
      'Updated the application version to v2.17.',
    ],
  },
  {
    version: 'v2.16',
    date: '2026-08-13',
    title: 'Ṣaḍbala: five approximations replaced with real calculations',
    changes: [
      'Cheṣṭā Bala now uses the classical eightfold motion (vakra, vikala, mandatara, manda, sama, chara, aticharā) measured from the planet’s real daily speed, which the ephemeris was already computing and discarding. The Sun takes its Ayana Bala and the Moon its Pakṣa Bala, per BPHS.',
      'Ayana Bala now uses each planet’s true declination from the ephemeris instead of a sine approximation, with the Sun’s value doubled as the classical rule requires.',
      'Natonnata Bala now uses real sunrise and sunset and varies continuously with distance from true local noon, instead of awarding all or nothing from the Sun’s house.',
      'Tribhāga Bala now divides the actual day and night into thirds instead of assuming a 6am sunrise.',
      'Saptavargaja Bala now recognizes Mūlatrikoṇa as its own dignity worth 45 virūpa, separate from an ordinary own sign at 30.',
      'Added sunrise and sunset calculation, validated against published times for Delhi, Helsinki, Quito and a polar case at Tromsø.',
      'Ṣaḍbala values will change for every chart. Only Dig and Dṛg Bala remain marked as approximations.',
      'Updated the application version to v2.16.',
    ],
  },
  {
    version: 'v2.15',
    date: '2026-08-13',
    title: 'Render loop fix and settings that survive reload',
    changes: [
      'Fixed a render loop that fired "Maximum update depth exceeded" in the browser console on every calculated chart.',
      'Fixed settings restore: Dasha toggles beyond BCP/Vimśottarī and all Chara and Rāśi method options previously reverted to defaults on every reload.',
      'Moved the Ṣaḍbala engine from the Varga Matrix page component into a typed calculation module with the other engines.',
      'Removed the Varāhamihira Aṣṭakavarga selector: after the v2.14 correction it differed from Parāśara by a single unverified row, so the choice was misleading. It returns if the Brihat Jataka table is verified against a primary source.',
      'Removed 22 never-implemented placeholder Dasha systems from the internal registry.',
      'Updated the application version to v2.15.',
    ],
  },
  {
    version: 'v2.14',
    date: '2026-08-13',
    title: 'Ashtakavarga correction and a working test suite',
    changes: [
      'Fixed the Parāśara Aṣṭakavarga table: the Sun, Mars and Mercury ascendant rows held a placeholder copy of a generic row, inflating their BAV totals to 50/42/55 and every SAV to 343.',
      'Aṣṭakavarga now matches the classical BPHS totals of 48/49/39/54/56/52/39 with an SAV of 337, so displayed bindu values will change.',
      'Fixed a rounding fault in longitude normalization that pushed planets sitting exactly on a varga boundary into the previous division.',
      'The 22 calculation fixtures now actually run: added an npm test script, and a CI workflow covering tests, typecheck and a production build.',
      'Rewrote the Ṣaḍbala fixture, which previously tested its own local copies of the constants instead of the application code.',
      'Added chart-independent golden vectors for Aṣṭakavarga and full composition checks for Bhāva Bala.',
      'Removed the unused BNN alpha, Pro, Jupiterian Rounds, Jupiter Minor and Event Detection panels left behind by earlier refactors.',
      'Updated the application version to v2.14.',
    ],
  },
  {
    version: 'v2.13',
    date: '2026-08-12',
    title: 'Event Timeline',
    changes: [
      'Added a chronological Event Timeline for all saved Event List records.',
      'Combined saved events with the related Mahadasha change markers from every enabled Dasha system.',
      'Added category, tag and Dasha-system filters plus an option to hide period changes.',
      'Event cards now expand to show notes, tags, significance and the complete active MD–AD–PD snapshot.',
      'Designed the timeline as a touch-friendly vertical view for mobile displays.',
      'Centralized Event List storage migration so Events and History read older saved data consistently.',
      'Updated the application version to v2.13.',
    ],
  },
  {
    version: 'v2.12',
    date: '2026-08-12',
    title: 'Dasha workspace mobile optimization',
    changes: [
      'Reworked the Dasha workspace navigation into a phone-friendly two-row grid with larger touch targets.',
      'Stacked Timeline and Finder controls on narrow screens and allowed result details to wrap without truncation.',
      'Improved Event List forms, filters, event headers and Dasha snapshots for 360–412 px displays.',
      'Replaced the mobile Overlap table with readable per-system cards while retaining the desktop table.',
      'Reformatted Nakshatra, Kalachakra and Rasi Dasha period rows to prevent dates and durations from colliding.',
      'Updated the application version to v2.12.',
    ],
  },
  {
    version: 'v2.11',
    date: '2026-08-12',
    title: 'Mobile Pattern Analysis layout',
    changes: [
      'Changed Pattern Analysis result cards to a stacked mobile layout so Dasha names, levels and values remain fully readable.',
      'Moved sample statistics below the pattern details on narrow screens and allowed long labels to wrap instead of truncating.',
      'Updated the application version to v2.11.',
    ],
  },
  {
    version: 'v2.10',
    date: '2026-08-12',
    title: 'Event intelligence and Dasha comparison',
    changes: [
      'Added notes, tags, significance ratings and search/filter controls to saved events, including import and export support.',
      'Upgraded Date Finder with any-level searches, AND/OR filter logic and CSV export.',
      'Added a Dasha Overlap tab comparing shared active values and the MD/AD/PD matrix for every enabled system.',
      'Upgraded Pattern Analysis with multi-level combinations, derived Rasi rulers, category support rates and sample-size confidence labels.',
      'Updated the application version to v2.10.',
    ],
  },
  {
    version: 'v2.00',
    date: '2026-08-12',
    title: 'Dasha workspace, backups and golden vectors',
    changes: [
      'Split Dasha tools into Timeline, Finder, Events, Patterns and Systems tabs.',
      'Added a full local-data backup and restore workflow covering saved charts, all Event Lists, settings, methods and workspace layout.',
      'Restore now validates the backup, previews its record count and requires explicit replacement confirmation.',
      'Aligned Rāśi Daśā dates to the JHora sidereal-year basis of 365.256364 days.',
      'Added three PyJHora source-derived golden vectors per Nārāyaṇa, Mūla and Sthira system covering seeds, orders, durations, continuity and dates.',
      'Kept the systems in Beta until direct exports from the JHora desktop application are available as a second independent dataset.',
      'Updated the application version to v2.00.',
    ],
  },
  {
    version: 'v1.93',
    date: '2026-08-12',
    title: 'PyJHora rule-reference validation',
    changes: [
      'Compared Nārāyaṇa, Mūla and Sthira progression, exception and duration rules against PyJHora commit 48e57d2.',
      'Fixed the Mūla Ketu-seed exception: Ketu in the seed sign now always forces reverse progression.',
      'Added a locked external-reference fixture covering the corrected Mūla Ketu exception.',
      'Calculation audits now identify the reference revision and distinguish rule parity from full date parity.',
      'The three systems remain Beta until complete independent golden-chart date comparisons pass.',
      'Updated the application version to v1.93.',
    ],
  },
  {
    version: 'v1.92',
    date: '2026-08-12',
    title: 'Event List import',
    changes: [
      'Added CSV and JSON imports for Event List data, including files exported by BCP.',
      'Added an import preview showing new, duplicate and rejected event counts before data is saved.',
      'CSV Dasha rows are collapsed back into unique events and existing duplicates are skipped.',
      'Added validation for event names, ISO dates, categories, vargas and a 2 MB file-size limit.',
      'Updated the application version to v1.92.',
    ],
  },
  {
    version: 'v1.91',
    date: '2026-08-12',
    title: 'Dasha Date Finder',
    changes: [
      'Added date-range searches for matching MD, AD and PD periods in every calculated Dasha system.',
      'Added partial-name matching and combined searches requiring the same criteria in multiple enabled systems.',
      'Consecutive matching days are grouped into periods instead of shown as duplicate daily rows.',
      'Finder results can set and open the shared timeline date and prefill the Event List date.',
      'Searches are capped at five years per run to keep browser-side calculation bounded.',
      'Updated the application version to v1.91.',
    ],
  },
  {
    version: 'v1.90',
    date: '2026-08-12',
    title: 'Recurring Dasha event patterns',
    changes: [
      'Added automatic detection of recurring MD, AD and PD rulers across saved events.',
      'Added event-category filters for comparing work, money, relationships, health and other event types.',
      'Pattern counts follow the currently enabled and visible Dasha systems.',
      'Added an explicit reminder that repetition is descriptive and does not prove causation.',
      'Updated the application version to v1.90.',
    ],
  },
  {
    version: 'v1.89',
    date: '2026-08-12',
    title: 'Rashi Dasha regression validation',
    changes: [
      'Added locked seed, period-order, continuity and duration checks for Nārāyaṇa, Mūla and Sthira Daśā.',
      'Added a visible regression verification result and fixture identifier to each Rāśi Daśā calculation audit.',
      'Kept the systems in Beta and explicitly separated internal regression coverage from independent JHora golden-chart parity.',
      'Updated the application version to v1.89.',
    ],
  },
  {
    version: 'v1.88',
    date: '2026-08-12',
    title: 'Dasha method settings',
    changes: [
      'Added a dedicated Dasha Methods section without restoring the removed Advanced section.',
      'Restored working Chara method controls for start sign, direction, subperiod start, duration counting, dignity adjustment and co-lords.',
      'Added Nārāyaṇa and Mūla seed variants with the PVR/JHora-compatible stronger Lagna/7th method as the default.',
      'Kept Sthira on the implemented PVR/JHora Brahma-seed method and clearly labelled exploratory Lagna-only variants.',
      'Method selections now remain synchronized across Dasha panels, the shared timeline and Event List exports.',
    ],
  },
  {
    version: 'v1.87',
    date: '2026-08-11',
    title: 'Event List 2.0',
    changes: [
      'Added editable event categories and D1/D7/D9/D10/D12/D60 analysis contexts.',
      'The Event List now shows only enabled Dasha systems and provides additional per-system visibility filters.',
      'Added CSV and JSON exports containing events and active MD–AD–PD periods.',
      'Added Set as transit to calculate the existing transit view for an event date and show the resulting transit positions in the event.',
      'Added calculated natal varga positions and a direct Open Varga Matrix action for every event.',
      'Existing saved events migrate automatically with Other and D1 defaults.',
    ],
  },
  {
    version: 'v1.86',
    date: '2026-08-11',
    title: 'Unified Dasha Timeline',
    changes: [
      'Added one shared timeline above the vertically stacked Dasha panels.',
      'Added a date selector, ±1-year navigation and Today shortcut for comparing active periods.',
      'Shows active MD–AD–PD paths and MD ranges for every enabled calculated system on a common ±10-year scale.',
      'Added direct links from timeline rows to the corresponding Dasha panel.',
      'Conditional Aṣṭottarī non-applicability is shown directly in the timeline.',
    ],
  },
  {
    version: 'v1.85',
    date: '2026-08-11',
    title: 'Dasha validation and conditional eligibility',
    changes: [
      'Added expandable calculation details to Nārāyaṇa, Mūla and Sthira Daśā, including seed, progression, duration basis and method variant.',
      'Marked the three new Rāśi systems as Beta until external golden-chart parity is certified.',
      'Added a chart-specific BPHS/PVR eligibility check to conditional Aṣṭottarī Daśā.',
      'When the Aṣṭottarī condition is not met, periods stay hidden unless Calculate anyway is selected; the Event List also reports non-applicability.',
    ],
  },
  {
    version: 'v1.84',
    date: '2026-08-11',
    title: 'Narayana, Mula and Sthira Dasha',
    changes: [
      'Added Nārāyaṇa, Mūla (Lagna Kendrādi Rāśi) and Sthira Daśā as full calculated systems.',
      'Added MD–AD–PD–SD–PR–DE navigation and Event List periods to all three systems.',
      'Added visible Rāśi/Nakshatra type labels and a Conditional badge for conditional Daśā systems.',
      'Updated the application version to v1.84.',
    ],
  },
  {
    version: 'v1.83',
    date: '2026-08-11',
    title: 'Simplified settings and Kalachakra placement',
    changes: [
      'Removed the separate Advanced settings section.',
      'Moved its chart overlay controls into the main Display section.',
      'Moved Kalachakra Dasha to the end of the main Dasha systems list.',
    ],
  },
  {
    version: 'v1.82',
    date: '2026-08-11',
    title: 'Yogini and Ashtottari Dasha',
    changes: [
      'Placed every enabled Dasha panel in one vertical column.',
      'Added Yogini Dasha with its 36-year cycle, birth balance and MD–AD–PD–SD–PR–DE navigation.',
      'Added conditional Ashtottari Dasha with its classical 108-year cycle and full sub-dasha navigation.',
      'Included the Abhijit segment and adjusted Uttara Ashadha and Shravana boundaries in Ashtottari birth-balance calculations.',
      'Included Yogini and Ashtottari MD–AD–PD periods in the Event List.',
    ],
  },
  {
    version: 'v1.81',
    date: '2026-08-11',
    title: 'Complete sub-dasha navigation',
    changes: [
      'Added MD–AD–PD–SD–PR–DE drill-down navigation to Chara and Kalachakra Dasha, matching both Vimsottari systems.',
      'Added complete active-now period paths and direct NOW navigation to every calculated Dasha panel.',
      'Removed the BNN highlight and BNN alpha settings toggles.',
      'Removed colored Nadi Paraya house-border overlays from the North Indian chart while keeping the Paraya labels.',
    ],
  },
  {
    version: 'v1.80',
    date: '2026-08-11',
    title: 'Automatic transits and streamlined analysis',
    changes: [
      'Removed Bhrigu Chakra Paddhati from Dasha panels, chart highlights, summaries and Workspace choices.',
      'Removed BNN Event Detection from desktop, mobile and Workspace navigation.',
      'Transit positions now initialize to the current time, recalculate automatically after date changes and remain visible on the natal chart.',
    ],
  },
  {
    version: 'v1.79',
    date: '2026-08-11',
    title: 'Dasha Event List',
    changes: [
      'Added a chart-specific Event List to the Dasha tab with persistent browser storage.',
      'Each event compares active Vimsottari, Vimsottari Original, Chara and Kalachakra periods for its date.',
      'Shows MD–AD–PD for Vimsottari and Chara, and MD–AD for Kalachakra.',
    ],
  },
  {
    version: 'v1.78',
    date: '2026-08-11',
    title: 'Dynamic paraya label layout',
    changes: [
      'Moved North Indian paraya labels into the same dynamic content stack as natal planets and special lagnas.',
      'Upper-house paraya labels appear immediately above planets; lower-house labels appear immediately below them.',
      'Corrected sign-label overlap in houses 8 and 12 and made spacing adapt to the number of planets in each house.',
    ],
  },
  {
    version: 'v1.77',
    date: '2026-08-11',
    title: 'Interactive Nadi paraya date calculator',
    changes: [
      'Added a date control that updates all Jupiter, Saturn, Rahu and Ketu paraya positions and chart highlights.',
      'Added an inverse calculator: choose a body, house and degree to see matching dates and apply one to the chart.',
      'Rahu and Ketu are calculated as an opposite axis, with matches shown across cycles up to age 120.',
      'Moved North Indian house 2 and house 11 labels away from triangle tips into clear interior positions.',
    ],
  },
  {
    version: 'v1.76',
    date: '2026-08-10',
    title: 'Paraya house alignment',
    changes: [
      'Added a dedicated safe label anchor and stacking direction for every North Indian chart house.',
      'Corrected Jupiter positioning in house 11 and Ketu positioning in house 2.',
      'Paraya labels now remain inside triangular and diamond-shaped house boundaries.',
    ],
  },
  {
    version: 'v1.75',
    date: '2026-08-10',
    title: 'Clearer paraya chart labels',
    changes: [
      'Improved Jupiter and Ketu contrast in active-house chart markers.',
      'Increased paraya marker font size and added a theme-aware outline behind North Indian chart labels.',
      'Stacked simultaneous activations and enlarged South Indian chart badges to prevent overlap.',
    ],
  },
  {
    version: 'v1.74',
    date: '2026-08-10',
    title: 'Nadi paraya degrees',
    changes: [
      'Added the exact in-sign progression degree for Jupiter, Saturn, Rahu and Ketu.',
      'Forward progressions advance from 0° to 30°; Rahu and Ketu move from 30° toward 0°.',
      'Current paraya degrees are shown both in the BNN cards and directly on North and South Indian charts.',
    ],
  },
  {
    version: 'v1.73',
    date: '2026-08-10',
    title: 'Nadi paraya chart highlights',
    changes: [
      'Added Jupiter, Saturn, Rahu and Ketu paraya activations directly to North and South Indian charts.',
      'Active houses use the same gold, blue, violet and orange colors as the paraya cards.',
      'Multiple paraya activations in one house remain visible side by side instead of covering each other.',
    ],
  },
  {
    version: 'v1.72',
    date: '2026-08-10',
    title: 'Nadi paraya colors',
    changes: [
      'Added distinct colors to Nadi paraya cards: Jupiter gold, Saturn blue, Rahu violet and Ketu orange.',
      'Colors are applied to the active sign, border and subtle background in both light and dark themes.',
    ],
  },
  {
    version: 'v1.71',
    date: '2026-08-10',
    title: 'Nadi paraya progressions',
    changes: [
      'Added unified Nadi paraya cards for Jupiter, Saturn, Rahu and Ketu in the BNN panel.',
      'Saturn follows the repeating 3–2 year pattern; Rahu and Ketu move backward with the repeating 2–1 year pattern.',
      'Retrograde natal Jupiter and Saturn begin their paraya activation one sign earlier.',
    ],
  },
  {
    version: 'v1.70',
    date: '2026-08-10',
    title: 'Custom Lahiri ayanamsa',
    changes: [
      'Added a Custom Lahiri choice with a signed degree adjustment: negative subtracts and positive adds.',
      'The adjustment is saved in calculation settings and applies to natal and transit planets, nodes and Lagna.',
      'The active adjustment is shown in the chart summary and exported report.',
    ],
  },
  {
    version: 'v1.69',
    date: '2026-08-10',
    title: 'Expanded ayanamsas',
    changes: [
      'Added Chandra-Hari/True Mūla, Wilhelm Mūla, Mardyks, Babylonian Britton and Ushāśaśi ayanamsas.',
      'Added ten common systems: Lahiri, Raman, KP, Fagan–Bradley, Yukteshwar, J.N. Bhasin, De Luce, Djwhal Khul, True Chitra and True Revati.',
      'All sidereal choices use their native Swiss Ephemeris mode and apply consistently to planets, nodes and Lagna.',
    ],
  },
  {
    version: 'v1.68',
    date: '2026-08-10',
    title: 'Sahams',
    changes: [
      'Added a separate expandable table of 36 Tajika Sahams under Grahas.',
      'Shows exact position, nakshatra/pada, whole-sign house, meaning and formula.',
      'Uses local sunrise/sunset for day/night formulas and applies the classical 30° correction.',
    ],
  },
  {
    version: 'v1.67',
    date: '2026-08-10',
    title: 'Planetary Avasthas',
    changes: [
      'Added a separate expandable Planetary Avasthas table under Grahas.',
      'Added Bālādi, Dīptādi, Jāgratādi, Lajjitādi and primary Śayanādi states with calculation details.',
      'Śayanādi uses the birth nakshatra, planetary nakshatra/navāṁśa, sunrise ghati and Lagna.',
    ],
  },
  {
    version: 'v1.66',
    date: '2026-08-10',
    title: 'Kālachakra birth-balance fix',
    changes: [
      'Fixed Kālachakra birth balance so the elapsed Moon-pāda fraction applies only to the first rāśi period, not the whole life cycle.',
      'Current mahādaśā periods now remain available for Moon positions near the end of a pada.',
      'Corrected first-period antardaśā balance and repeated-sign cycle selection.',
    ],
  },
  {
    version: 'v1.65',
    date: '2026-08-10',
    title: 'Public Charts directory',
    changes: [
      'Added a dedicated Public tab for opening ready-made public-figure charts.',
      'Added direct Astro-Databank name search plus Astro-Seek and Astrotheme directories.',
      'Added source-quality guidance for Rodden ratings and uncertain birth times.',
    ],
  },
  {
    version: 'v1.64',
    date: '2026-08-10',
    title: 'Chara Daśā timeline',
    changes: [
      'Promoted Chara Daśā from experimental output to a complete core timeline.',
      'Added dated mahādaśā rows, active-period highlighting and drill-down antardaśās.',
      'Retained the selectable Lagna/Ātmakāraka, direction, lord and duration rules.',
    ],
  },
  {
    version: 'v1.63',
    date: '2026-08-10',
    title: 'Kālachakra Daśā',
    changes: [
      'Added the Moon-pāda based Kālachakra rāśi-daśā using the classical savya/apasavya tables.',
      'Shows birth balance, mahādaśā and drill-down antardaśā dates, plus Deha and Jīva signs.',
      'Removed the duplicate Kaal Chakra/Kalachakra placeholders from settings.',
    ],
  },
  {
    version: 'v1.62',
    date: '2026-08-10',
    title: 'Parāśara and Varāhamihira Aṣṭakavarga',
    changes: [
      'Added selectable Parāśara and Varāhamihira calculation tables.',
      'Applied the selected system to both the numeric table and North Indian chart.',
      'Colored only the point numbers: green above neutral, red below neutral, and black at neutral.',
    ],
  },
  {
    version: 'v1.61',
    date: '2026-08-10',
    title: 'North Indian Aṣṭakavarga chart',
    changes: [
      'Added a North Indian chart view inside the separate Aṣṭakavarga section.',
      'SAV or an individual planet BAV can be selected; houses display point numbers only.',
    ],
  },
  {
    version: 'v1.60',
    date: '2026-08-10',
    title: 'Separate Aṣṭakavarga table',
    changes: [
      'Moved Bhinna and Sarva Aṣṭakavarga values into their own chart tab.',
      'Removed the AV overlay and its setting from natal charts.',
      'Aligned house-based bindu values to fixed zodiac-sign columns; cells now show numbers only.',
    ],
  },
  {
    version: 'v1.59',
    changes: [
      'Added selectable Chara Karaka ranking: classical highest degree or highest minute',
      'Highest-minute mode compares the minute–second remainder and reverses Rahu before ranking',
      'Added deterministic tests for both Chara Karaka ranking modes',
    ],
  },
  {
    version: 'v1.58',
    changes: [
      'Added all 150 Deva Keralam / Chandra Kala Nadi nāḍī-aṁśa names',
      'Nāḍī table now shows the calculated name together with its number and sign modality',
    ],
  },
  {
    version: 'v1.57',
    changes: [
      'Added a dedicated Nāḍī tab for Lagna and graha calculations',
      'Deva Keralam: 150 equal 0°12′ divisions with movable, fixed, and dual sign ordering',
      'Siddhar: separate equal D150 harmonic placement with pūrva/para 0°06′ halves',
      'Added boundary tests for sign modalities, 15° dual-sign reset, and nāḍī halves',
    ],
  },
  {
    version: 'v1.56',
    changes: [
      'BNN simplified into single Event Detection module; removed standalone Jupiterian Rounds and Minor Progression panels',
      'BNN Event Detection context now shows natal Jupiter sign/degree, balance, current round number, and Temporary Lagna',
      'BNN Event Detection panel is collapsible; age override cleared with one click',
      'Removed Pada, Pada108, and D108 Experimental columns from Graha Table',
      'Removed BNN Jupiterian Rounds and BNN Jupiter Minor settings toggles',
      'Ashtakavarga handling corrected: shows "Ashtakavarga not available yet" instead of unreliable values',
    ],
  },
  {
    version: 'v1.55',
    changes: [
      'Bhava Bala: added occupant (Bhava Graha) contribution — ~approx: benefic occupant +45 × Ṣaḍbala ratio, malefic −30 × ratio virupa',
      'Bhava Bala: Bhavadhipati column now shows lord virupa, required minimum, and ratio transparently (source from Ṣaḍbala)',
      'Bhava Bala: ~Bhava Dig Bala expanded — kendra +15 vp, panapara +7.5 vp, apoklima 0 vp (labeled approximate)',
      'Bhava Bala: expandable per-house debug row shows lord source, each occupant with contribution, each aspecting planet with contribution and aspect strength, and explicit A+B+C=total formula',
      'Bhava Bala: Status column added — strong/ok/weak relative to chart mean (not a fixed threshold)',
      'Bhava Bala: negative contributions visible in Drig− column and occupant column for malefic planets',
      'Added bhavaBala.test.ts: deterministic verification fixture with fully worked H1 and H4 manual calculations',
    ],
  },
  {
    version: 'v1.54',
    changes: [
      'Shadbala rewritten to use classical virūpa totals and planet-specific minimum thresholds',
      'All six Shadbala components now stored and displayed in virūpa (not rūpa decimals)',
      'Naisargika Bala updated to exact classical integer values: Sun 60, Moon 51, Venus 43, Jupiter 34, Mercury 26, Mars 17, Saturn 9',
      'Planet-specific required minimums in virūpa: Sun 390, Moon 360, Mars 300, Mercury 420, Jupiter 390, Venus 330, Saturn 300',
      'Strength percentage calculated as totalVirupa / requiredVirupa × 100',
      'UI now shows raw virūpa total, required minimum, percentage, and status (weak/ok/strong with colour coding)',
      'Dṛg Bala now allows negative values where malefic aspects reduce strength (classical convention)',
      'Debug table marks approximate components with ~ prefix (Saptavargaja, Dig, Natonnata, Tribhaga, Ayana, Cheṣṭā, Dṛg)',
    ],
  },
  {
    version: 'v1.53',
    changes: [
      'Bhava Bala beta: replaced heuristic 0–100 scoring with classical Bhavesha + Bhava Drig calculation',
      'Bhavesha Bala now uses the lord\'s actual Ṣaḍbala (virupa) computed from the same chart data',
      'Bhava Drig uses orb-based drishti to the house sign midpoint — four components (strong/weak × benefic/malefic)',
      'Kendra bonus: +15 virupa for angular houses (H1, H4, H7, H10), per classical convention',
      'Values now in virupa (no arbitrary 0–100 normalisation); heuristic Quality column removed',
      'Code comments clarify what is implemented and what is not yet (Digbala, Kala Bala, cusp-based Drig)',
    ],
  },
  {
    version: 'v1.52',
    changes: [
      'Varga Matrix, Varga Strength / Viṁśopaka Bala, Shadbala beta, and Bhava Bala beta are now independent Workspace panels',
      'Each section can be added as a standalone Workspace panel and toggled independently',
      'Existing Chart Render → Varga combined view preserved unchanged',
    ],
  },
  {
    version: 'v1.51',
    changes: [
      'Removed Target Date from the main page input area.',
      'Renamed Run BCP action to Calculate Chart for clearer UX.',
    ],
  },
  {
    version: 'v1.48',
    changes: [
      'Inactive yogas hidden by default — only active yogas are shown in the Yoga Table',
      'Yoga Table can now be added as a standalone Workspace panel',
      'Workspace now supports up to 8 panels (was 4)',
      'Added Mukuta, Raja, Sakata, Dhana, Chandra, Adhi, Uttama, Sama and Adhama yogas',
      'Added Pancha Mahapurusha yogas: Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn)',
    ],
  },
  {
    version: 'v1.47',
    changes: [
      'Added Yoga Table with Vosi, Vesi, Ubhayachari, Anapha, Sunapha, Durudhara and Kemadruma yoga detection.',
    ],
  },
  {
    version: 'v1.44',
    changes: [
      'Added configurable degree precision: Off, rounded degrees, degrees + minutes, and degrees + minutes + seconds. Transit planets now follow the same degree display setting.',
      'Transit datetime controls now visible under main chart and in Natal+Transit workspace panel',
      'BCP age/month manual override controls now appear under the main chart when BCP is enabled',
      'Legend items are now panel-specific in workspace: BCP legend only in BCP panel, BNN legend only in BNN panel, transit legend only in Natal+Transit panel',
      'Natal and Natal+Transit workspace panels no longer show BCP legend items',
    ],
  },
  {
    version: 'v1.43',
    changes: [
      'Fixed BNN age override chart syncing — override state lifted to page level, chart highlights update instantly',
      'Added BCP age controls below BCP chart in workspace panels',
      'Fixed retrograde detection — SEFLG_SPEED flag now correctly passed to Swiss Ephemeris (all grahas, not just nodes)',
      'BNN age override shared across BNN tab and workspace BNN panels',
    ],
  },
  {
    version: 'v1.42',
    changes: [
      'Retrograde planets now show ℞ in chart, Graha Table — Rahu/Ketu always marked retrograde',
      'BCP Override and BCP Summary now hidden when BCP dasha is turned off',
      'Workspace mode opens full-width on desktop (chart column collapses)',
      'BNN age override syncs to chart highlight colors via lifted state',
    ],
  },
  {
    version: 'v1.41',
    changes: [
      'Added multi-chart workspace mode with independent panels for BNN, BCP, Natal+Transit, Vimshottari and Graha Table',
      'Each workspace panel independently controls which highlights are shown (BNN vs BCP vs none)',
      'Desktop: 2–3 column responsive grid; mobile: stacked with per-panel collapse',
      'Add up to 4 panels; panel type changes via dropdown; panel configuration persists across sessions',
    ],
  },
  {
    version: 'v1.40',
    changes: [
      'Added BNN Event Detection panel combining Jupiterian Rounds and Minor Progression into interpretable event windows',
      'Event categories: marriage, career, property, children, father/authority, wealth/family, spirituality, health/pressure, foreign travel, education',
      'Confidence levels (high/medium/low) based on dual-layer activation scoring',
      'Moved raw BNN engine output behind Advanced BNN Engine Debug toggle (off by default)',
    ],
  },
  {
    version: 'v1.39',
    changes: [
      'Added BNN Jupiterian Rounds panel with natal Jupiter degree based rounds',
      'Active rashi / temporary lagna from natal Jupiter sign progression',
      'Age controls: auto-computed from birth + target date, with manual override',
      'Graha activation table: house from temporary lagna, sorted 1–12, with karakatwa',
      'Sun karakatwa reflects BNN timing layer (Fame, Talent, Government, etc.) — not Parashari dasha',
    ],
  },
  {
    version: 'v1.38',
    changes: [
      'BNN v2: planetary chain engine (depth-2 and depth-3 ordered chains)',
      'Multi-factor chain scoring: conjunction +10, trine +5, Jupiter/Saturn presence, Ketu/Rahu modifiers',
      'Signal filtering: top-5–7 findings with guaranteed Saturn / Jupiter / Moon coverage',
      'Structured output: Key Patterns, Support Factors, Risk Factors (Ketu / Ra-Mo)',
      'Rahu chains flagged as unstable in UI',
    ],
  },
  {
    version: 'v1.37',
    changes: [
      'BNN Relationship Engine: graha-to-graha analysis (conjunction, 2nd, 5th, 7th, 9th, 12th)',
      'Topic-based readings: Career, Marriage, Education, Wealth, Children, Spirituality, Health, General',
      'Anchor Graha selector with Auto (topic anchors) or specific graha',
      'Confidence scoring (high/medium/low) and strength scoring per finding',
      'Full relation map table (collapsible)',
    ],
  },
  {
    version: 'v1.36',
    changes: [
      'BNN Pro: ordered trinal chain engine (Fire / Earth / Air / Water circuits)',
      'Degree sequence matters — Venus → Moon and Moon → Venus carry distinct meanings',
      'Chain activation model: dasha planets and transits (sign conjunction + 7th aspect)',
    ],
  },
  {
    version: 'v1.35',
    changes: [
      'Added Graha Drishti (planetary aspects)',
      'Added Rashi Drishti (Jaimini sign aspects)',
      'New Drishti tab with house-level summary',
      'Independent nakshatra zodiac mode: sidereal (Lahiri, default) or tropical — separate from ayanamsa sign setting',
      'BCP manual override moved from Data tab to Dasha tab where it belongs',
      'BNN Alpha module: clearly labeled research-only rule cards for planet placements and conjunctions',
      'Data section cleaned up: birth data only, no mixed BCP controls',
    ],
  },
  {
    version: 'v1.34',
    changes: [
      'Added full Ashtakavarga system (Bhinna + Sarva)',
      'Added chart overlay for Ashtakavarga',
    ],
  },
  {
    version: 'v1.26',
    changes: [
      'Simple mode UX cleanup: removed debug labels (chart.render, $ run bcp) from user-facing view',
      'BCP summary panel with human-readable year/month house themes shown below the chart in Simple mode',
      'Compact calculation summary strip (ayanamsa, node mode, timezone) visible near the chart',
      'Resolved SettingsPanel merge conflict; split display toggles into basic and advanced sections properly',
      'Special lagna highlight color changed to amber to avoid clash with the BCP "both houses" purple',
      'South Indian chart legend is now conditional — only shown when BCP highlights / transit / special lagnas are active',
      'Mobile chart and card readability improvements: cells use overflow-hidden and truncation',
    ],
  },
];
