import { APP_NAME, APP_VERSION } from './config';
import { ChartData, BcpResult, CalculationSettings } from '@/types';
import { CharaKaraka } from '@/lib/karakas';

const SIGN_NAMES: Record<number, string> = {
  1: 'Aries',    2: 'Taurus',     3: 'Gemini',      4: 'Cancer',
  5: 'Leo',      6: 'Virgo',      7: 'Libra',        8: 'Scorpio',
  9: 'Sagittarius', 10: 'Capricorn', 11: 'Aquarius', 12: 'Pisces',
};

export interface ReportInput {
  birthDatetime: string;
  city: string;
  ianaTimezone: string;
  effectiveTzOffset: number | null;
  latitude: number;
  longitude: number;
  chart: ChartData | null;
  charaKarakas: CharaKaraka[];
  bcp: BcpResult | null;
  calculationSettings?: CalculationSettings;
}

function fmtOffset(offset: number): string {
  const sign = offset >= 0 ? '+' : '';
  return `${sign}${offset % 1 === 0 ? offset.toFixed(0) : offset.toFixed(1)}h UTC`;
}

export function buildReportMarkdown(input: ReportInput): string {
  const lines: string[] = [];

  lines.push(`# ${APP_NAME} ${APP_VERSION} — Jyotish Chart Report`);
  lines.push('');

  lines.push('## Birth Data');
  lines.push(`- Date/Time: ${input.birthDatetime}`);
  if (input.city) lines.push(`- Location: ${input.city}`);
  if (input.ianaTimezone) lines.push(`- Timezone: ${input.ianaTimezone}`);
  if (input.effectiveTzOffset !== null) lines.push(`- UTC Offset: ${fmtOffset(input.effectiveTzOffset)}`);
  if (!isNaN(input.latitude))  lines.push(`- Latitude: ${input.latitude}`);
  if (!isNaN(input.longitude)) lines.push(`- Longitude: ${input.longitude}`);

  if (input.chart) {
    const { ascendant, planets } = input.chart;
    lines.push('');
    lines.push('## Ascendant');
    lines.push(`- Sign: ${SIGN_NAMES[ascendant.sign] ?? ascendant.sign} (${ascendant.sign})`);
    lines.push(`- Degree: ${ascendant.degree.toFixed(4)}°`);

    lines.push('');
    lines.push('## Grahas (Sidereal · Lahiri · Whole-Sign Houses)');
    lines.push('| Graha | Sign | Degree | House |');
    lines.push('|---|---|---|---|');
    for (const p of planets) {
      lines.push(`| ${p.name} | ${SIGN_NAMES[p.sign] ?? p.sign} | ${p.degree.toFixed(4)}° | H${p.house} |`);
    }
  }

  if (input.charaKarakas.length > 0) {
    lines.push('');
    lines.push('## Chara Karakas');
    lines.push('| Karaka | Planet | Degree |');
    lines.push('|---|---|---|');
    for (const k of input.charaKarakas) {
      lines.push(`| ${k.karaka} (${k.karakaFull}) | ${k.planet} | ${k.degree.toFixed(4)}° |`);
    }
  }

  if (input.bcp) {
    const { bcp } = input;
    lines.push('');
    lines.push('## BCP Summary');
    lines.push(`- Completed Age: ${bcp.completedAge}`);
    lines.push(`- Running Year: ${bcp.runningYear}`);
    lines.push(`- BCP Cycle: ${bcp.bcpCycle}`);
    lines.push(`- Month in Year: ${bcp.monthInRunningYear}`);
    lines.push(`- Active Year House: H${bcp.activeYearHouse}`);
    lines.push(`- Active Month House: H${bcp.activeMonthHouse}`);
  }

  if (input.chart?.debug) {
    const d = input.chart.debug;
    lines.push('');
    lines.push('## Calculation Details');
    lines.push(`- Ephemeris: ${d.ephemerisEngine}`);
    lines.push(`- Julian Day: ${d.julianDay.toFixed(4)}`);
    lines.push(`- Ayanamsa (Lahiri): ${d.ayanamsa.toFixed(6)}°`);
    lines.push(`- Input Date/Time: ${d.inputDateTime}`);
    if (input.ianaTimezone) lines.push(`- Timezone: ${input.ianaTimezone}`);
    lines.push(`- UTC Offset: ${fmtOffset(d.utcOffset)}`);
    lines.push(`- Latitude: ${d.latitude}`);
    lines.push(`- Longitude: ${d.longitude}`);
  }

  lines.push('');
  lines.push('---');
  const ayanamsa = input.calculationSettings?.ayanamsa ?? 'lahiri';
  const nodeMode = input.calculationSettings?.nodeMode ?? 'mean';
  lines.push(`Generated by ${APP_NAME} ${APP_VERSION} · ${ayanamsa} ayanamsa · whole-sign houses · ${nodeMode} nodes`);

  return lines.join('\n');
}
