import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { calculateChart } from './ephemeris';
import { calculateRasiDasha, RASI_ABBR, type RasiDashaSystem } from './rasiDashas';
import { brahma, strongerSign, toJaiminiChart } from './jaiminiStrength';

// ---------------------------------------------------------------------------
// The book's own worked examples, from P.V.R. Narasimha Rao's "Vedic
// Astrology: An Integrated Approach" (as carried in PyJHora's test suite),
// cast with this app's ephemeris. Sign and years for the first twelve
// Nārāyaṇa periods.
// ---------------------------------------------------------------------------
const BOOK = [
  {
    label: 'Example 66 / Chart 23',
    birth: [1912, 8, 8, 19, 38, 0], lat: 13, lng: 77 + 35 / 60, tz: 5.5,
    narayana: 'Le1 Cp8 Ge2 Sc9 Ar4 Vi1 Aq9 Cn3 Sg11 Ta3 Li10 Pi4',
  },
  {
    label: 'Exercise 27 / Chart 21',
    birth: [1960, 11, 25, 0, 22, 0], lat: 38 + 54 / 60, lng: -77 - 2 / 60, tz: -5,
    narayana: 'Aq2 Vi11 Ar2 Sc3 Ge4 Cp1 Le9 Pi3 Li2 Ta7 Sg12 Cn5',
  },
] as const;

const sequence = (system: RasiDashaSystem, planets: Parameters<typeof calculateRasiDasha>[1], asc: number, count = 12) =>
  calculateRasiDasha(system, planets, asc, new Date(0)).entries.slice(0, count)
    .map((e) => `${RASI_ABBR[e.sign]}${e.durationYears}`).join(' ');

// ---------------------------------------------------------------------------
// PyJHora 4.8.7 run on randomly generated charts. Each fixture carries the
// planet positions PyJHora used, so the comparison tests the rules alone and
// not the two ephemerides. Generated by running PyJHora's
// narayana_dhasa_for_rasi_chart, lagna_kendradhi_rasi_dhasa,
// sthira.get_dhasa_antardhasa, _narayana_antardhasa, house.brahma and
// house.stronger_rasi_from_planet_positions.
// ---------------------------------------------------------------------------
type Fixture = {
  asc: number;
  planets: [number, number][];
  seed: number;
  brahma: number;
  narayana: [number, number][];
  kendradhi: [number, number][];
  sthira: [number, number][];
  narayanaAd: Record<string, number[]>;
};
const NAMES = ['Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter', 'Venus', 'Saturn', 'Rahu', 'Ketu'];
const fixtures: Fixture[] = JSON.parse(readFileSync(new URL('./fixtures/rasiDashaPyjhora.json', import.meta.url), 'utf8'));
const expected = (rows: [number, number][], count = 24) =>
  rows.filter(([, years]) => years > 0).slice(0, count).map(([s, y]) => `${RASI_ABBR[s]}${y}`).join(' ');

async function main() {
  for (const example of BOOK) {
    const [y, mo, d, h, mi, s] = example.birth;
    const chart = await calculateChart(y, mo, d, h, mi, s, example.lat, example.lng, example.tz);
    assert.equal(sequence('narayana', chart.planets, chart.ascendant.sign), example.narayana, `${example.label} Nārāyaṇa`);
  }

  assert.ok(fixtures.length >= 8, 'fixture set is present');
  fixtures.forEach((f, index) => {
    const planets = f.planets.map(([sign, degree], i) => ({ name: NAMES[i], sign: sign + 1, degree, longitude: sign * 30 + degree }));
    const asc = f.asc + 1;
    const label = `PyJHora fixture ${index}`;
    const chart = toJaiminiChart(planets, asc);
    assert.equal(strongerSign(chart, f.asc, (f.asc + 6) % 12), f.seed, `${label}: stronger of lagna and 7th`);
    assert.equal(brahma(chart), NAMES[f.brahma], `${label}: Brahma`);
    assert.equal(sequence('narayana', planets, asc, 24), expected(f.narayana), `${label}: Nārāyaṇa`);
    assert.equal(sequence('moola', planets, asc, 24), expected(f.kendradhi), `${label}: Lagna Kendrādi (Mūla)`);
    assert.equal(sequence('sthira', planets, asc), expected(f.sthira, 12), `${label}: Sthira`);
    const result = calculateRasiDasha('narayana', planets, asc, new Date(0));
    for (const entry of result.entries.filter((e) => e.cycle === 1)) {
      assert.deepEqual(entry.childOrder, f.narayanaAd[String(entry.sign)], `${label}: antardaśās of ${RASI_ABBR[entry.sign]}`);
    }
  });
  console.log(`Rāśi daśās agree with the book examples and ${fixtures.length} PyJHora charts`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
