'use client';
import { useState } from 'react';
import { createBcpBackup, parseBcpBackup, restoreBcpBackup, type BcpBackup } from '@/lib/localBackup';
function download(content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `bhrigu-code-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
export default function BackupPanel() {
  const [preview, setPreview] = useState<BcpBackup | null>(null); const [message, setMessage] = useState('');
  function exportAll() { const backup = createBcpBackup(localStorage); download(JSON.stringify(backup, null, 2)); setMessage(`Backed up ${Object.keys(backup.entries).length} local data records.`); }
  async function read(file?: File) { if (!file) return; if (file.size > 5_000_000) return setMessage('Backup exceeds the 5 MB limit.'); try { setPreview(parseBcpBackup(await file.text())); setMessage(''); } catch { setPreview(null); setMessage('Invalid or unsupported BCP backup.'); } }
  function restore() { if (!preview) return; const count = restoreBcpBackup(preview, localStorage); setMessage(`Restored ${count} records. Reloading…`); setPreview(null); window.setTimeout(() => window.location.reload(), 400); }
  return <div className="space-y-2 rounded-md border border-zinc-200 p-3 dark:border-zinc-700"><div className="text-[10px] font-mono uppercase tracking-widest text-zinc-400">Full local backup</div><p className="text-[10px] text-zinc-500">Includes saved charts, all Event Lists, calculation and display settings, Dasha methods and workspace layout.</p><div className="flex flex-wrap gap-2"><button type="button" onClick={exportAll} className="rounded border border-emerald-400 px-2 py-1.5 text-xs text-emerald-700 dark:text-emerald-300">Download backup</button><label className="cursor-pointer rounded border border-cyan-400 px-2 py-1.5 text-xs text-cyan-700 dark:text-cyan-300">Choose backup<input type="file" accept=".json,application/json" className="hidden" onChange={event => { void read(event.target.files?.[0]); event.target.value = ''; }}/></label></div>{preview && <div className="rounded border border-amber-300 bg-amber-50 p-2 text-[10px] dark:border-amber-800 dark:bg-amber-950/20"><p><strong>{Object.keys(preview.entries).length}</strong> records · created {preview.createdAt || 'unknown'}. Restoring replaces all current BCP local data on this device.</p><div className="mt-2 flex gap-2"><button type="button" onClick={() => setPreview(null)} className="rounded border px-2 py-1">Cancel</button><button type="button" onClick={restore} className="rounded bg-amber-700 px-2 py-1 font-semibold text-white">Replace and restore</button></div></div>}{message && <p className="text-[10px] text-zinc-500">{message}</p>}</div>;
}
